version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8500:8500"  # Keep original port
    volumes:
      - ./frontend/app:/app/app
      - ./frontend/app/static:/app/static
    environment:
      - BACKEND_URL=http://backend:8000
      - STREAMLIT_SERVER_PORT=8500  # Set Streamlit port
    command: streamlit run --server.port 8500 app/streamlit_app.py
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./model_retrain:/app/model_retrain  # Maps container path to local path
      - ./models:/app/models
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
