# Update dvc.yaml to include data preprocessing:
stages:
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    outs:
    - models/attention_unet.pth
    metrics:
    - metrics.json
    params:
    - params.yaml:train
