global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "windows_exporter"
    static_configs:
      - targets: ["host.docker.internal:9182"]
