scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'windows'
    static_configs:
      - targets: ['host.docker.internal:9182']
    scrape_interval: 5s